import { StyleSheet } from '@react-pdf/renderer';

export const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 25,
    paddingBottom: 65,
    paddingHorizontal: 25,
    fontFamily: 'Helvetica',
    fontSize: 8.5,
    color: '#334155',
    lineHeight: 1.4,
  },
  topSection: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1.5,
    borderBottomColor: '#1e3a8a',
    paddingBottom: 8,
    marginBottom: 12,
  },
  empresaBloco: {
    width: '50%',
  },
  empresaNome: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1e3a8a',
    letterSpacing: -0.5,
  },
  empresaNuit: {
    fontSize: 7.5,
    color: '#475569',
    marginTop: 4,
  },
  clienteTopoBloco: {
    width: '45%',
    textAlign: 'right',
  },
  docTitulo: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#0f172a',
    marginBottom: 2,
  },
  clienteTextoPequeno: {
    fontSize: 7.5,
    color: '#64748b',
    marginBottom: 1,
  },
  seccaoTitulo: {
    fontSize: 8,
    fontWeight: 'bold',
    color: '#1e3a8a',
    backgroundColor: '#eff6ff',
    paddingVertical: 3,
    paddingHorizontal: 6,
    borderRadius: 2,
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  viaturaBarra: {
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 4,
    padding: 6,
    marginBottom: 10,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  viaturaTexto: {
    fontSize: 8.5,
    color: '#0f172a',
  },
  vinDestaque: {
    fontWeight: 'bold',
    color: '#dc2626',
  },
  materialContainer: {
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 4,
    padding: 6,
    marginBottom: 10,
    backgroundColor: '#f8fafc',
  },
  listaItensGrid: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    marginTop: 4,
  },
  badgeItem: {
    backgroundColor: '#e2e8f0',
    color: '#0f172a',
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 3,
    fontSize: 7.5,
  },
  termosSeccao: {
    backgroundColor: '#f8fafc',
    padding: 6,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginBottom: 15,
  },
  termosTexto: {
    fontSize: 7,
    color: '#64748b',
    textAlign: 'justify',
    marginBottom: 3,
  },
  assinaturaContainer: {
    marginTop: 15,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  assinaturaBloco: {
    width: '45%',
    textAlign: 'center',
  },
  linhaAssinatura: {
    borderTopWidth: 1,
    borderTopColor: '#94a3b8',
    paddingTop: 4,
    fontSize: 8,
    fontWeight: 'bold',
    color: '#0f172a',
  },
  dataLocal: {
    fontSize: 7.5,
    color: '#64748b',
    marginTop: 2,
  },
  footerEmpresa: {
    position: 'absolute',
    bottom: 20,
    left: 25,
    right: 25,
    borderTopWidth: 1,
    borderTopColor: '#cbd5e1',
    paddingTop: 6,
    textAlign: 'center',
  },
  footerLinhaTexto: {
    fontSize: 7,
    color: '#64748b',
    marginBottom: 1,
  }
});