import React from 'react';

export const s: Record<string, React.CSSProperties> = {
  // ─── Layout base ──────────────────────────────────────────────────────────
  page: {
    backgroundColor: '#f8fafc',
    minHeight: '100vh',
    fontFamily: 'Inter, system-ui, sans-serif',
    color: '#0f172a',
  },

  // ─── Banner / Hero ────────────────────────────────────────────────────────
  banner: {
    background: 'linear-gradient(180deg, #ffffff 0%, #f1f5f9 100%)',
    padding: 'clamp(24px, 5vw, 40px) 24px 28px 24px',
    textAlign: 'center',
    borderBottom: '1px solid #e2e8f0',
  },
  badge: {
    backgroundColor: '#eff6ff',
    color: '#2563eb',
    padding: '4px 14px',
    borderRadius: '20px',
    fontSize: '12px',
    fontWeight: 700,
    display: 'inline-block',
    marginBottom: '10px',
    letterSpacing: '0.03em',
  },
  h1: {
    fontSize: 'clamp(22px, 3vw + 12px, 36px)',
    fontWeight: 850,
    color: '#0f172a',
    letterSpacing: '-0.03em',
    margin: '0 0 8px 0',
    lineHeight: 1.2,
  },
  subtitle: {
    color: '#475569',
    fontSize: '15px',
    maxWidth: '640px',
    margin: '0 auto',
    lineHeight: '1.5',
    fontWeight: 400,
  },

  // ─── Trust strip (novo) ───────────────────────────────────────────────────
  trustStrip: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    justifyContent: 'center',
    gap: '8px',
    marginTop: '20px',
  },
  trustPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    backgroundColor: 'rgba(255,255,255,0.85)',
    border: '1px solid #cbd5e1',
    borderRadius: '999px',
    padding: '5px 14px',
    fontSize: '12px',
    fontWeight: 600,
    color: '#1e3a8a',
  },

  // ─── Main container ───────────────────────────────────────────────────────
  main: {
    maxWidth: '960px',
    margin: '0 auto 60px auto',
    padding: '24px 16px 0 16px',
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: '20px',
    padding: 'clamp(16px, 4vw, 28px)',
    boxShadow: '0 8px 24px -8px rgba(15,23,42,0.08)',
    border: '1px solid #e2e8f0',
  },

  // ─── Campo VIN ────────────────────────────────────────────────────────────
  fieldLabel: {
    fontSize: '11px',
    fontWeight: 700,
    color: '#475569',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    marginBottom: '5px',
  },
  inputRow: {
    display: 'flex',
    width: '100%',
    borderRadius: '12px',
    overflow: 'hidden',
    border: '2px solid #e2e8f0',
    minHeight: '52px',          // era height fixo — agora minHeight
  },
  vinInput: {
    flex: 1,
    minWidth: 0,                // impede overflow em flex
    padding: '0 18px',
    border: 'none',
    textTransform: 'uppercase' as const,
    fontWeight: 700,
    fontSize: '15px',
    outline: 'none',
    backgroundColor: '#fff',
    color: '#0f172a',
  },
  searchBtn: {
    width: '72px',
    flexShrink: 0,              // novo — não encolhe em viewports estreitas
    backgroundColor: '#1e40af',
    color: '#fff',
    border: 'none',
    cursor: 'pointer',
    fontSize: '18px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  helpLink: {
    background: 'none',
    border: 'none',
    color: '#2563eb',
    fontSize: '12px',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '5px',
    padding: '4px 0',
    marginTop: '5px',
  },

  // ─── Pesquisa alternativa (novo) ──────────────────────────────────────────
  altSearchBar: {
    marginTop: '14px',
    borderTop: '1px solid #f1f5f9',
    paddingTop: '12px',
    textAlign: 'center' as const,
    fontSize: '12px',
    color: '#94a3b8',
  },
  altSearchLink: {
    background: 'none',
    border: 'none',
    color: '#2563eb',
    fontWeight: 600,
    cursor: 'pointer',
    fontSize: '12px',
    padding: 0,
  },

  // ─── Painel de ajuda VIN ──────────────────────────────────────────────────
  helpPanel: {
    backgroundColor: '#f8fafc',
    border: '1px solid #e2e8f0',
    borderRadius: '12px',
    padding: '16px',
    marginTop: '12px',
  },
  helpGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(260px, 100%), 1fr))',
    gap: '12px',
  },
  helpBlock: {
    backgroundColor: '#fff',
    padding: '14px',
    borderRadius: '10px',
    border: '1px solid #e2e8f0',
  },
  helpBlockTitle: {
    fontSize: '11px',
    fontWeight: 800,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
    display: 'block',
    marginBottom: '6px',
  },
  mono: {
    backgroundColor: '#f1f5f9',
    padding: '8px 10px',
    borderRadius: '6px',
    fontSize: '11.5px',
    fontFamily: 'monospace',
    color: '#1e293b',
    borderLeft: '3px solid #2563eb',
    lineHeight: 1.5,
  },

  // ─── Loading ──────────────────────────────────────────────────────────────
  loading: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '14px 16px',
    backgroundColor: '#f8fafc',
    color: '#2563eb',
    fontWeight: 600,
    borderRadius: '12px',
    marginTop: '16px',
    border: '1px dashed #cbd5e1',
    fontSize: '13px',
  },

  // ─── Formulário manual ────────────────────────────────────────────────────
  errorBanner: {
    backgroundColor: '#fef2f2',
    color: '#991b1b',
    padding: '12px 16px',
    borderRadius: '12px 12px 0 0',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    border: '1px solid #fee2e2',
    borderBottom: 'none',
    fontSize: '13px',
    fontWeight: 600,
  },
  manualForm: {
    backgroundColor: '#ffffff',
    border: '1px solid #fee2e2',
    borderRadius: '0 0 12px 12px',
    padding: '20px',
  },
  manualGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(160px, 100%), 1fr))',  // era 180px
    gap: '12px',
    marginBottom: '14px',
  },
  mField: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '4px',
  },
  mLabel: {
    fontSize: '10px',
    fontWeight: 700,
    color: '#475569',
    textTransform: 'uppercase' as const,
  },
  mInput: {
    padding: '10px 14px',
    borderRadius: '8px',
    border: '1px solid #cbd5e1',
    fontWeight: 600,
    fontSize: '13px',
    outline: 'none',
  },
  manualFooter: {
    display: 'flex',
    flexWrap: 'wrap' as const,   // novo — quebra linha em mobile
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#fdf2f2',
    padding: '10px 14px',
    borderRadius: '8px',
    border: '1px dashed #fca5a5',
    gap: '12px',
  },
  manualNote: {
    fontSize: '11.5px',
    color: '#991b1b',
    fontWeight: 500,
  },
  btnAdvance: {
    backgroundColor: '#ef4444',
    color: '#fff',
    border: 'none',
    padding: '10px 20px',
    borderRadius: '8px',
    fontWeight: 700,
    cursor: 'pointer',
    fontSize: '13px',
    whiteSpace: 'nowrap' as const,
  },

  // ─── Divisor ──────────────────────────────────────────────────────────────
  divider: {
    borderTop: '1px solid #f1f5f9',
    margin: '20px 0',
  },

  // ─── Ficha técnica ────────────────────────────────────────────────────────
  fichaTitleRow: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '14px',
  },
  fichaTitle: {
    fontSize: '15px',
    color: '#0f172a',
    fontWeight: 800,
    margin: 0,
    letterSpacing: '-0.01em',
    display: 'flex',
    alignItems: 'center',
    gap: '7px',
  },
  manualBadge: {
    backgroundColor: '#fff7ed',
    color: '#c2410c',
    border: '1px solid #ffedd5',
    padding: '3px 10px',
    borderRadius: '6px',
    fontSize: '11px',
    fontWeight: 700,
  },
  fichaGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(140px, 100%), 1fr))',  // era 160px
    gap: '10px',
    marginBottom: '20px',
  },
  fichaCell: {
    backgroundColor: '#f8fafc',
    padding: '12px 16px',
    borderRadius: '10px',
    border: '1px solid #e2e8f0',
  },

  // ─── Configurador de peças ────────────────────────────────────────────────
  configBox: {
    backgroundColor: '#f8fafc',
    padding: '18px',
    borderRadius: '14px',
    border: '1px solid #e2e8f0',
    marginBottom: '20px',
  },
  configTitle: {
    fontSize: '12px',
    fontWeight: 700,
    color: '#475569',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.04em',
    marginBottom: '12px',
  },
  addRow: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '10px',
    alignItems: 'center',
  },
  autocompleteWrap: {
    position: 'relative' as const,
    flex: '1 1 180px',          // era flex: 2, minWidth: '220px'
    minWidth: 0,
  },
  pecaInput: {
    width: '100%',
    padding: '0 14px',
    height: '44px',
    borderRadius: '10px',
    border: '1px solid #cbd5e1',
    fontWeight: 600,
    fontSize: '13px',
    outline: 'none',
    backgroundColor: '#fff',
    color: '#0f172a',
    boxSizing: 'border-box' as const,
  },
  dropdown: {
    position: 'absolute' as const,
    top: '46px',
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    border: '1px solid #e2e8f0',
    borderRadius: '10px',
    boxShadow: '0 8px 20px rgba(0,0,0,0.08)',
    zIndex: 100,
    overflow: 'hidden',
  },
  dropdownItem: {
    padding: '9px 14px',
    fontSize: '13px',
    cursor: 'pointer',
    color: '#0f172a',
    borderBottom: '1px solid #f1f5f9',
    fontWeight: 500,
  },
  dropdownItemHover: {
    backgroundColor: '#eff6ff',
    color: '#1e40af',
  },
  qtyBox: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    backgroundColor: '#fff',
    padding: '0 12px',
    borderRadius: '10px',
    border: '1px solid #cbd5e1',
    height: '44px',
    flexShrink: 0,              // novo
  },
  qtyLabel: {
    fontSize: '12px',
    fontWeight: 700,
    color: '#64748b',
  },
  qtyInput: {
    width: '44px',
    border: 'none',
    fontWeight: 700,
    textAlign: 'center' as const,
    fontSize: '14px',
    outline: 'none',
    color: '#0f172a',
  },
  addBtn: {
    padding: '0 18px',
    backgroundColor: '#2563eb',
    color: '#fff',
    border: 'none',
    borderRadius: '10px',
    fontWeight: 700,
    height: '44px',
    cursor: 'pointer',
    fontSize: '13px',
    flexShrink: 0,              // novo — não encolhe
    whiteSpace: 'nowrap' as const,
  },

  // ─── Tags de peças ────────────────────────────────────────────────────────
  tagList: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '7px',
    marginTop: '14px',
    borderTop: '1px solid #e2e8f0',
    paddingTop: '14px',
  },
  tag: {
    backgroundColor: '#fff',
    padding: '5px 12px',
    borderRadius: '8px',
    fontSize: '12px',
    fontWeight: 600,
    display: 'inline-flex',
    alignItems: 'center',
    gap: '7px',
    border: '1px solid #e2e8f0',
    color: '#334155',
  },
  tagQty: {
    backgroundColor: '#f1f5f9',
    color: '#1e40af',
    padding: '1px 7px',
    borderRadius: '5px',
    fontSize: '11px',
    border: '1px solid #d9e2ec',
  },
  tagRemove: {
    color: '#ef4444',
    border: 'none',
    background: 'none',
    cursor: 'pointer',
    fontSize: '15px',
    padding: 0,
    fontWeight: 700,
  },

  // ─── Acções finais ────────────────────────────────────────────────────────
  actionRow: {
    display: 'flex',
    flexWrap: 'wrap' as const,  // novo — quebra em mobile
    gap: '10px',
    width: '100%',
  },
  btnCancel: {
    flex: '0 0 auto',
    minWidth: '120px',
    padding: '14px',
    backgroundColor: '#fef2f2',
    color: '#ef4444',
    border: '1px solid #fecade',
    borderRadius: '12px',
    fontWeight: 700,
    fontSize: '14px',
    cursor: 'pointer',
  },
  btnPrimary: {
    flex: 1,
    minWidth: '160px',          // novo — mínimo antes de quebrar linha
    padding: '14px',
    backgroundColor: '#16a34a',
    color: '#fff',
    border: 'none',
    borderRadius: '12px',
    fontWeight: 800,
    fontSize: '15px',
    cursor: 'pointer',
    boxShadow: '0 8px 16px -4px rgba(22,163,74,0.25)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
  },

  // ─── Múltiplos registos JDM ───────────────────────────────────────────────
  multipleTitle: {
    fontSize: '13px',
    color: '#b91c1c',
    fontWeight: 800,
    letterSpacing: '0.04em',
    textTransform: 'uppercase' as const,
    marginBottom: '12px',
  },
  multipleItem: {
    padding: '14px 16px',
    backgroundColor: '#f8fafc',
    border: '1px solid #e2e8f0',
    borderRadius: '12px',
    cursor: 'pointer',
    display: 'flex',
    flexWrap: 'wrap' as const,
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '10px',
  },
  multipleItemBtn: {
    padding: '6px 14px',
    backgroundColor: '#e0f2fe',
    color: '#0369a1',
    border: 'none',
    borderRadius: '7px',
    fontWeight: 700,
    fontSize: '12px',
    cursor: 'pointer',
    flexShrink: 0,
  },
};
